

export const SNACKBAR_TRIGGER = 'SNACKBAR_TRIGGER'
export const STATUS_API = 'STATUS_API'

export const PUBLIC_DATA_GET_REQUEST = 'PUBLIC_DATA_GET_REQUEST'
export const PUBLIC_DATA_GET_RECEIVE = 'PUBLIC_DATA_GET_RECEIVE'

